name = "hypersignal"
compatibility_date = "2024-10-10"
main = "cloudflare/worker.ts"
workers_dev = true

[build]
command = "npm run build"
directory = ".next"

[[d1_databases]]
binding = "DB"
database_name = "hypersignal"
database_id = ""
migrations_dir = "migrations"

[triggers]
crons = ["*/5 * * * *"]
